/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AngeboteRouteImport } from './routes/angebote'
import { Route as AntragRouteRouteImport } from './routes/antrag/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BestaetigungRouteImport } from './routes/bestaetigung'
import { Route as BestellenRouteImport } from './routes/bestellen'
import { Route as BewertungenRouteImport } from './routes/bewertungen'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HeizoelWissenRouteImport } from './routes/heizoel-wissen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LieferungZahlungRouteImport } from './routes/lieferung-zahlung'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AntragFertigRouteImport } from './routes/antrag/fertig'
import { Route as AntragSchritt1RouteImport } from './routes/antrag/schritt-1'
import { Route as AntragSchritt10RouteImport } from './routes/antrag/schritt-10'
import { Route as AntragSchritt11RouteImport } from './routes/antrag/schritt-11'
import { Route as AntragSchritt12RouteImport } from './routes/antrag/schritt-12'
import { Route as AntragSchritt13RouteImport } from './routes/antrag/schritt-13'
import { Route as AntragSchritt14RouteImport } from './routes/antrag/schritt-14'
import { Route as AntragSchritt15RouteImport } from './routes/antrag/schritt-15'
import { Route as AntragSchritt16RouteImport } from './routes/antrag/schritt-16'
import { Route as AntragSchritt17RouteImport } from './routes/antrag/schritt-17'
import { Route as AntragSchritt18RouteImport } from './routes/antrag/schritt-18'
import { Route as AntragSchritt2RouteImport } from './routes/antrag/schritt-2'
import { Route as AntragSchritt3RouteImport } from './routes/antrag/schritt-3'
import { Route as AntragSchritt4RouteImport } from './routes/antrag/schritt-4'
import { Route as AntragSchritt5RouteImport } from './routes/antrag/schritt-5'
import { Route as AntragSchritt6RouteImport } from './routes/antrag/schritt-6'
import { Route as AntragSchritt7RouteImport } from './routes/antrag/schritt-7'
import { Route as AntragSchritt8RouteImport } from './routes/antrag/schritt-8'
import { Route as AntragSchritt9RouteImport } from './routes/antrag/schritt-9'
import { Route as HeizoelpreiseIndexRouteImport } from './routes/heizoelpreise.index'
import { Route as HeizoelpreiseCityRouteImport } from './routes/heizoelpreise.$city'
import { Route as KreditantragApplicationIdRouteImport } from './routes/kreditantrag.$applicationId'
import { Route as PreisrechnerIndexRouteImport } from './routes/preisrechner.index'
import { Route as PreisrechnerErgebnisRouteImport } from './routes/preisrechner.ergebnis'
import { Route as HeizoelpreiseBundeslandStateRouteImport } from './routes/heizoelpreise.bundesland.$state'
import { Route as AuthenticatedAdminAntragApplicationIdRouteImport } from './routes/_authenticated/admin.antrag.$applicationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AngeboteRoute = AngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => rootRouteImport,
} as any)
const AntragRouteRoute = AntragRouteRouteImport.update({
  id: '/antrag',
  path: '/antrag',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BestaetigungRoute = BestaetigungRouteImport.update({
  id: '/bestaetigung',
  path: '/bestaetigung',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellenRoute = BestellenRouteImport.update({
  id: '/bestellen',
  path: '/bestellen',
  getParentRoute: () => rootRouteImport,
} as any)
const BewertungenRoute = BewertungenRouteImport.update({
  id: '/bewertungen',
  path: '/bewertungen',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HeizoelWissenRoute = HeizoelWissenRouteImport.update({
  id: '/heizoel-wissen',
  path: '/heizoel-wissen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LieferungZahlungRoute = LieferungZahlungRouteImport.update({
  id: '/lieferung-zahlung',
  path: '/lieferung-zahlung',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AntragFertigRoute = AntragFertigRouteImport.update({
  id: '/fertig',
  path: '/fertig',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt1Route = AntragSchritt1RouteImport.update({
  id: '/schritt-1',
  path: '/schritt-1',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt10Route = AntragSchritt10RouteImport.update({
  id: '/schritt-10',
  path: '/schritt-10',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt11Route = AntragSchritt11RouteImport.update({
  id: '/schritt-11',
  path: '/schritt-11',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt12Route = AntragSchritt12RouteImport.update({
  id: '/schritt-12',
  path: '/schritt-12',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt13Route = AntragSchritt13RouteImport.update({
  id: '/schritt-13',
  path: '/schritt-13',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt14Route = AntragSchritt14RouteImport.update({
  id: '/schritt-14',
  path: '/schritt-14',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt15Route = AntragSchritt15RouteImport.update({
  id: '/schritt-15',
  path: '/schritt-15',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt16Route = AntragSchritt16RouteImport.update({
  id: '/schritt-16',
  path: '/schritt-16',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt17Route = AntragSchritt17RouteImport.update({
  id: '/schritt-17',
  path: '/schritt-17',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt18Route = AntragSchritt18RouteImport.update({
  id: '/schritt-18',
  path: '/schritt-18',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt2Route = AntragSchritt2RouteImport.update({
  id: '/schritt-2',
  path: '/schritt-2',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt3Route = AntragSchritt3RouteImport.update({
  id: '/schritt-3',
  path: '/schritt-3',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt4Route = AntragSchritt4RouteImport.update({
  id: '/schritt-4',
  path: '/schritt-4',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt5Route = AntragSchritt5RouteImport.update({
  id: '/schritt-5',
  path: '/schritt-5',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt6Route = AntragSchritt6RouteImport.update({
  id: '/schritt-6',
  path: '/schritt-6',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt7Route = AntragSchritt7RouteImport.update({
  id: '/schritt-7',
  path: '/schritt-7',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt8Route = AntragSchritt8RouteImport.update({
  id: '/schritt-8',
  path: '/schritt-8',
  getParentRoute: () => AntragRouteRoute,
} as any)
const AntragSchritt9Route = AntragSchritt9RouteImport.update({
  id: '/schritt-9',
  path: '/schritt-9',
  getParentRoute: () => AntragRouteRoute,
} as any)
const HeizoelpreiseIndexRoute = HeizoelpreiseIndexRouteImport.update({
  id: '/heizoelpreise/',
  path: '/heizoelpreise/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeizoelpreiseCityRoute = HeizoelpreiseCityRouteImport.update({
  id: '/heizoelpreise/$city',
  path: '/heizoelpreise/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const KreditantragApplicationIdRoute =
  KreditantragApplicationIdRouteImport.update({
    id: '/kreditantrag/$applicationId',
    path: '/kreditantrag/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreisrechnerIndexRoute = PreisrechnerIndexRouteImport.update({
  id: '/preisrechner/',
  path: '/preisrechner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreisrechnerErgebnisRoute = PreisrechnerErgebnisRouteImport.update({
  id: '/preisrechner/ergebnis',
  path: '/preisrechner/ergebnis',
  getParentRoute: () => rootRouteImport,
} as any)
const HeizoelpreiseBundeslandStateRoute =
  HeizoelpreiseBundeslandStateRouteImport.update({
    id: '/heizoelpreise/bundesland/$state',
    path: '/heizoelpreise/bundesland/$state',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAntragApplicationIdRoute =
  AuthenticatedAdminAntragApplicationIdRouteImport.update({
    id: '/antrag/$applicationId',
    path: '/antrag/$applicationId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antrag': typeof AntragRouteRouteWithChildren
  '/angebote': typeof AngeboteRoute
  '/auth': typeof AuthRoute
  '/bestaetigung': typeof BestaetigungRoute
  '/bestellen': typeof BestellenRoute
  '/bewertungen': typeof BewertungenRoute
  '/faq': typeof FaqRoute
  '/heizoel-wissen': typeof HeizoelWissenRoute
  '/kontakt': typeof KontaktRoute
  '/lieferung-zahlung': typeof LieferungZahlungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/antrag/fertig': typeof AntragFertigRoute
  '/antrag/schritt-1': typeof AntragSchritt1Route
  '/antrag/schritt-10': typeof AntragSchritt10Route
  '/antrag/schritt-11': typeof AntragSchritt11Route
  '/antrag/schritt-12': typeof AntragSchritt12Route
  '/antrag/schritt-13': typeof AntragSchritt13Route
  '/antrag/schritt-14': typeof AntragSchritt14Route
  '/antrag/schritt-15': typeof AntragSchritt15Route
  '/antrag/schritt-16': typeof AntragSchritt16Route
  '/antrag/schritt-17': typeof AntragSchritt17Route
  '/antrag/schritt-18': typeof AntragSchritt18Route
  '/antrag/schritt-2': typeof AntragSchritt2Route
  '/antrag/schritt-3': typeof AntragSchritt3Route
  '/antrag/schritt-4': typeof AntragSchritt4Route
  '/antrag/schritt-5': typeof AntragSchritt5Route
  '/antrag/schritt-6': typeof AntragSchritt6Route
  '/antrag/schritt-7': typeof AntragSchritt7Route
  '/antrag/schritt-8': typeof AntragSchritt8Route
  '/antrag/schritt-9': typeof AntragSchritt9Route
  '/heizoelpreise/$city': typeof HeizoelpreiseCityRoute
  '/kreditantrag/$applicationId': typeof KreditantragApplicationIdRoute
  '/preisrechner/ergebnis': typeof PreisrechnerErgebnisRoute
  '/heizoelpreise/': typeof HeizoelpreiseIndexRoute
  '/preisrechner/': typeof PreisrechnerIndexRoute
  '/heizoelpreise/bundesland/$state': typeof HeizoelpreiseBundeslandStateRoute
  '/admin/antrag/$applicationId': typeof AuthenticatedAdminAntragApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antrag': typeof AntragRouteRouteWithChildren
  '/angebote': typeof AngeboteRoute
  '/auth': typeof AuthRoute
  '/bestaetigung': typeof BestaetigungRoute
  '/bestellen': typeof BestellenRoute
  '/bewertungen': typeof BewertungenRoute
  '/faq': typeof FaqRoute
  '/heizoel-wissen': typeof HeizoelWissenRoute
  '/kontakt': typeof KontaktRoute
  '/lieferung-zahlung': typeof LieferungZahlungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/antrag/fertig': typeof AntragFertigRoute
  '/antrag/schritt-1': typeof AntragSchritt1Route
  '/antrag/schritt-10': typeof AntragSchritt10Route
  '/antrag/schritt-11': typeof AntragSchritt11Route
  '/antrag/schritt-12': typeof AntragSchritt12Route
  '/antrag/schritt-13': typeof AntragSchritt13Route
  '/antrag/schritt-14': typeof AntragSchritt14Route
  '/antrag/schritt-15': typeof AntragSchritt15Route
  '/antrag/schritt-16': typeof AntragSchritt16Route
  '/antrag/schritt-17': typeof AntragSchritt17Route
  '/antrag/schritt-18': typeof AntragSchritt18Route
  '/antrag/schritt-2': typeof AntragSchritt2Route
  '/antrag/schritt-3': typeof AntragSchritt3Route
  '/antrag/schritt-4': typeof AntragSchritt4Route
  '/antrag/schritt-5': typeof AntragSchritt5Route
  '/antrag/schritt-6': typeof AntragSchritt6Route
  '/antrag/schritt-7': typeof AntragSchritt7Route
  '/antrag/schritt-8': typeof AntragSchritt8Route
  '/antrag/schritt-9': typeof AntragSchritt9Route
  '/heizoelpreise/$city': typeof HeizoelpreiseCityRoute
  '/kreditantrag/$applicationId': typeof KreditantragApplicationIdRoute
  '/preisrechner/ergebnis': typeof PreisrechnerErgebnisRoute
  '/heizoelpreise': typeof HeizoelpreiseIndexRoute
  '/preisrechner': typeof PreisrechnerIndexRoute
  '/heizoelpreise/bundesland/$state': typeof HeizoelpreiseBundeslandStateRoute
  '/admin/antrag/$applicationId': typeof AuthenticatedAdminAntragApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/antrag': typeof AntragRouteRouteWithChildren
  '/angebote': typeof AngeboteRoute
  '/auth': typeof AuthRoute
  '/bestaetigung': typeof BestaetigungRoute
  '/bestellen': typeof BestellenRoute
  '/bewertungen': typeof BewertungenRoute
  '/faq': typeof FaqRoute
  '/heizoel-wissen': typeof HeizoelWissenRoute
  '/kontakt': typeof KontaktRoute
  '/lieferung-zahlung': typeof LieferungZahlungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/antrag/fertig': typeof AntragFertigRoute
  '/antrag/schritt-1': typeof AntragSchritt1Route
  '/antrag/schritt-10': typeof AntragSchritt10Route
  '/antrag/schritt-11': typeof AntragSchritt11Route
  '/antrag/schritt-12': typeof AntragSchritt12Route
  '/antrag/schritt-13': typeof AntragSchritt13Route
  '/antrag/schritt-14': typeof AntragSchritt14Route
  '/antrag/schritt-15': typeof AntragSchritt15Route
  '/antrag/schritt-16': typeof AntragSchritt16Route
  '/antrag/schritt-17': typeof AntragSchritt17Route
  '/antrag/schritt-18': typeof AntragSchritt18Route
  '/antrag/schritt-2': typeof AntragSchritt2Route
  '/antrag/schritt-3': typeof AntragSchritt3Route
  '/antrag/schritt-4': typeof AntragSchritt4Route
  '/antrag/schritt-5': typeof AntragSchritt5Route
  '/antrag/schritt-6': typeof AntragSchritt6Route
  '/antrag/schritt-7': typeof AntragSchritt7Route
  '/antrag/schritt-8': typeof AntragSchritt8Route
  '/antrag/schritt-9': typeof AntragSchritt9Route
  '/heizoelpreise/$city': typeof HeizoelpreiseCityRoute
  '/kreditantrag/$applicationId': typeof KreditantragApplicationIdRoute
  '/preisrechner/ergebnis': typeof PreisrechnerErgebnisRoute
  '/heizoelpreise/': typeof HeizoelpreiseIndexRoute
  '/preisrechner/': typeof PreisrechnerIndexRoute
  '/heizoelpreise/bundesland/$state': typeof HeizoelpreiseBundeslandStateRoute
  '/_authenticated/admin/antrag/$applicationId': typeof AuthenticatedAdminAntragApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antrag'
    | '/angebote'
    | '/auth'
    | '/bestaetigung'
    | '/bestellen'
    | '/bewertungen'
    | '/faq'
    | '/heizoel-wissen'
    | '/kontakt'
    | '/lieferung-zahlung'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/antrag/fertig'
    | '/antrag/schritt-1'
    | '/antrag/schritt-10'
    | '/antrag/schritt-11'
    | '/antrag/schritt-12'
    | '/antrag/schritt-13'
    | '/antrag/schritt-14'
    | '/antrag/schritt-15'
    | '/antrag/schritt-16'
    | '/antrag/schritt-17'
    | '/antrag/schritt-18'
    | '/antrag/schritt-2'
    | '/antrag/schritt-3'
    | '/antrag/schritt-4'
    | '/antrag/schritt-5'
    | '/antrag/schritt-6'
    | '/antrag/schritt-7'
    | '/antrag/schritt-8'
    | '/antrag/schritt-9'
    | '/heizoelpreise/$city'
    | '/kreditantrag/$applicationId'
    | '/preisrechner/ergebnis'
    | '/heizoelpreise/'
    | '/preisrechner/'
    | '/heizoelpreise/bundesland/$state'
    | '/admin/antrag/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antrag'
    | '/angebote'
    | '/auth'
    | '/bestaetigung'
    | '/bestellen'
    | '/bewertungen'
    | '/faq'
    | '/heizoel-wissen'
    | '/kontakt'
    | '/lieferung-zahlung'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/antrag/fertig'
    | '/antrag/schritt-1'
    | '/antrag/schritt-10'
    | '/antrag/schritt-11'
    | '/antrag/schritt-12'
    | '/antrag/schritt-13'
    | '/antrag/schritt-14'
    | '/antrag/schritt-15'
    | '/antrag/schritt-16'
    | '/antrag/schritt-17'
    | '/antrag/schritt-18'
    | '/antrag/schritt-2'
    | '/antrag/schritt-3'
    | '/antrag/schritt-4'
    | '/antrag/schritt-5'
    | '/antrag/schritt-6'
    | '/antrag/schritt-7'
    | '/antrag/schritt-8'
    | '/antrag/schritt-9'
    | '/heizoelpreise/$city'
    | '/kreditantrag/$applicationId'
    | '/preisrechner/ergebnis'
    | '/heizoelpreise'
    | '/preisrechner'
    | '/heizoelpreise/bundesland/$state'
    | '/admin/antrag/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/antrag'
    | '/angebote'
    | '/auth'
    | '/bestaetigung'
    | '/bestellen'
    | '/bewertungen'
    | '/faq'
    | '/heizoel-wissen'
    | '/kontakt'
    | '/lieferung-zahlung'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/antrag/fertig'
    | '/antrag/schritt-1'
    | '/antrag/schritt-10'
    | '/antrag/schritt-11'
    | '/antrag/schritt-12'
    | '/antrag/schritt-13'
    | '/antrag/schritt-14'
    | '/antrag/schritt-15'
    | '/antrag/schritt-16'
    | '/antrag/schritt-17'
    | '/antrag/schritt-18'
    | '/antrag/schritt-2'
    | '/antrag/schritt-3'
    | '/antrag/schritt-4'
    | '/antrag/schritt-5'
    | '/antrag/schritt-6'
    | '/antrag/schritt-7'
    | '/antrag/schritt-8'
    | '/antrag/schritt-9'
    | '/heizoelpreise/$city'
    | '/kreditantrag/$applicationId'
    | '/preisrechner/ergebnis'
    | '/heizoelpreise/'
    | '/preisrechner/'
    | '/heizoelpreise/bundesland/$state'
    | '/_authenticated/admin/antrag/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AntragRouteRoute: typeof AntragRouteRouteWithChildren
  AngeboteRoute: typeof AngeboteRoute
  AuthRoute: typeof AuthRoute
  BestaetigungRoute: typeof BestaetigungRoute
  BestellenRoute: typeof BestellenRoute
  BewertungenRoute: typeof BewertungenRoute
  FaqRoute: typeof FaqRoute
  HeizoelWissenRoute: typeof HeizoelWissenRoute
  KontaktRoute: typeof KontaktRoute
  LieferungZahlungRoute: typeof LieferungZahlungRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  HeizoelpreiseCityRoute: typeof HeizoelpreiseCityRoute
  KreditantragApplicationIdRoute: typeof KreditantragApplicationIdRoute
  PreisrechnerErgebnisRoute: typeof PreisrechnerErgebnisRoute
  HeizoelpreiseIndexRoute: typeof HeizoelpreiseIndexRoute
  PreisrechnerIndexRoute: typeof PreisrechnerIndexRoute
  HeizoelpreiseBundeslandStateRoute: typeof HeizoelpreiseBundeslandStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebote': {
      id: '/angebote'
      path: '/angebote'
      fullPath: '/angebote'
      preLoaderRoute: typeof AngeboteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antrag': {
      id: '/antrag'
      path: '/antrag'
      fullPath: '/antrag'
      preLoaderRoute: typeof AntragRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestaetigung': {
      id: '/bestaetigung'
      path: '/bestaetigung'
      fullPath: '/bestaetigung'
      preLoaderRoute: typeof BestaetigungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellen': {
      id: '/bestellen'
      path: '/bestellen'
      fullPath: '/bestellen'
      preLoaderRoute: typeof BestellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewertungen': {
      id: '/bewertungen'
      path: '/bewertungen'
      fullPath: '/bewertungen'
      preLoaderRoute: typeof BewertungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heizoel-wissen': {
      id: '/heizoel-wissen'
      path: '/heizoel-wissen'
      fullPath: '/heizoel-wissen'
      preLoaderRoute: typeof HeizoelWissenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieferung-zahlung': {
      id: '/lieferung-zahlung'
      path: '/lieferung-zahlung'
      fullPath: '/lieferung-zahlung'
      preLoaderRoute: typeof LieferungZahlungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/antrag/fertig': {
      id: '/antrag/fertig'
      path: '/fertig'
      fullPath: '/antrag/fertig'
      preLoaderRoute: typeof AntragFertigRouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-1': {
      id: '/antrag/schritt-1'
      path: '/schritt-1'
      fullPath: '/antrag/schritt-1'
      preLoaderRoute: typeof AntragSchritt1RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-10': {
      id: '/antrag/schritt-10'
      path: '/schritt-10'
      fullPath: '/antrag/schritt-10'
      preLoaderRoute: typeof AntragSchritt10RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-11': {
      id: '/antrag/schritt-11'
      path: '/schritt-11'
      fullPath: '/antrag/schritt-11'
      preLoaderRoute: typeof AntragSchritt11RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-12': {
      id: '/antrag/schritt-12'
      path: '/schritt-12'
      fullPath: '/antrag/schritt-12'
      preLoaderRoute: typeof AntragSchritt12RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-13': {
      id: '/antrag/schritt-13'
      path: '/schritt-13'
      fullPath: '/antrag/schritt-13'
      preLoaderRoute: typeof AntragSchritt13RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-14': {
      id: '/antrag/schritt-14'
      path: '/schritt-14'
      fullPath: '/antrag/schritt-14'
      preLoaderRoute: typeof AntragSchritt14RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-15': {
      id: '/antrag/schritt-15'
      path: '/schritt-15'
      fullPath: '/antrag/schritt-15'
      preLoaderRoute: typeof AntragSchritt15RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-16': {
      id: '/antrag/schritt-16'
      path: '/schritt-16'
      fullPath: '/antrag/schritt-16'
      preLoaderRoute: typeof AntragSchritt16RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-17': {
      id: '/antrag/schritt-17'
      path: '/schritt-17'
      fullPath: '/antrag/schritt-17'
      preLoaderRoute: typeof AntragSchritt17RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-18': {
      id: '/antrag/schritt-18'
      path: '/schritt-18'
      fullPath: '/antrag/schritt-18'
      preLoaderRoute: typeof AntragSchritt18RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-2': {
      id: '/antrag/schritt-2'
      path: '/schritt-2'
      fullPath: '/antrag/schritt-2'
      preLoaderRoute: typeof AntragSchritt2RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-3': {
      id: '/antrag/schritt-3'
      path: '/schritt-3'
      fullPath: '/antrag/schritt-3'
      preLoaderRoute: typeof AntragSchritt3RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-4': {
      id: '/antrag/schritt-4'
      path: '/schritt-4'
      fullPath: '/antrag/schritt-4'
      preLoaderRoute: typeof AntragSchritt4RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-5': {
      id: '/antrag/schritt-5'
      path: '/schritt-5'
      fullPath: '/antrag/schritt-5'
      preLoaderRoute: typeof AntragSchritt5RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-6': {
      id: '/antrag/schritt-6'
      path: '/schritt-6'
      fullPath: '/antrag/schritt-6'
      preLoaderRoute: typeof AntragSchritt6RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-7': {
      id: '/antrag/schritt-7'
      path: '/schritt-7'
      fullPath: '/antrag/schritt-7'
      preLoaderRoute: typeof AntragSchritt7RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-8': {
      id: '/antrag/schritt-8'
      path: '/schritt-8'
      fullPath: '/antrag/schritt-8'
      preLoaderRoute: typeof AntragSchritt8RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/antrag/schritt-9': {
      id: '/antrag/schritt-9'
      path: '/schritt-9'
      fullPath: '/antrag/schritt-9'
      preLoaderRoute: typeof AntragSchritt9RouteImport
      parentRoute: typeof AntragRouteRoute
    }
    '/heizoelpreise/': {
      id: '/heizoelpreise/'
      path: '/heizoelpreise'
      fullPath: '/heizoelpreise/'
      preLoaderRoute: typeof HeizoelpreiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heizoelpreise/$city': {
      id: '/heizoelpreise/$city'
      path: '/heizoelpreise/$city'
      fullPath: '/heizoelpreise/$city'
      preLoaderRoute: typeof HeizoelpreiseCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kreditantrag/$applicationId': {
      id: '/kreditantrag/$applicationId'
      path: '/kreditantrag/$applicationId'
      fullPath: '/kreditantrag/$applicationId'
      preLoaderRoute: typeof KreditantragApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preisrechner/': {
      id: '/preisrechner/'
      path: '/preisrechner'
      fullPath: '/preisrechner/'
      preLoaderRoute: typeof PreisrechnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preisrechner/ergebnis': {
      id: '/preisrechner/ergebnis'
      path: '/preisrechner/ergebnis'
      fullPath: '/preisrechner/ergebnis'
      preLoaderRoute: typeof PreisrechnerErgebnisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heizoelpreise/bundesland/$state': {
      id: '/heizoelpreise/bundesland/$state'
      path: '/heizoelpreise/bundesland/$state'
      fullPath: '/heizoelpreise/bundesland/$state'
      preLoaderRoute: typeof HeizoelpreiseBundeslandStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/antrag/$applicationId': {
      id: '/_authenticated/admin/antrag/$applicationId'
      path: '/antrag/$applicationId'
      fullPath: '/admin/antrag/$applicationId'
      preLoaderRoute: typeof AuthenticatedAdminAntragApplicationIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAntragApplicationIdRoute: typeof AuthenticatedAdminAntragApplicationIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAntragApplicationIdRoute:
    AuthenticatedAdminAntragApplicationIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AntragRouteRouteChildren {
  AntragFertigRoute: typeof AntragFertigRoute
  AntragSchritt1Route: typeof AntragSchritt1Route
  AntragSchritt10Route: typeof AntragSchritt10Route
  AntragSchritt11Route: typeof AntragSchritt11Route
  AntragSchritt12Route: typeof AntragSchritt12Route
  AntragSchritt13Route: typeof AntragSchritt13Route
  AntragSchritt14Route: typeof AntragSchritt14Route
  AntragSchritt15Route: typeof AntragSchritt15Route
  AntragSchritt16Route: typeof AntragSchritt16Route
  AntragSchritt17Route: typeof AntragSchritt17Route
  AntragSchritt18Route: typeof AntragSchritt18Route
  AntragSchritt2Route: typeof AntragSchritt2Route
  AntragSchritt3Route: typeof AntragSchritt3Route
  AntragSchritt4Route: typeof AntragSchritt4Route
  AntragSchritt5Route: typeof AntragSchritt5Route
  AntragSchritt6Route: typeof AntragSchritt6Route
  AntragSchritt7Route: typeof AntragSchritt7Route
  AntragSchritt8Route: typeof AntragSchritt8Route
  AntragSchritt9Route: typeof AntragSchritt9Route
}

const AntragRouteRouteChildren: AntragRouteRouteChildren = {
  AntragFertigRoute: AntragFertigRoute,
  AntragSchritt1Route: AntragSchritt1Route,
  AntragSchritt10Route: AntragSchritt10Route,
  AntragSchritt11Route: AntragSchritt11Route,
  AntragSchritt12Route: AntragSchritt12Route,
  AntragSchritt13Route: AntragSchritt13Route,
  AntragSchritt14Route: AntragSchritt14Route,
  AntragSchritt15Route: AntragSchritt15Route,
  AntragSchritt16Route: AntragSchritt16Route,
  AntragSchritt17Route: AntragSchritt17Route,
  AntragSchritt18Route: AntragSchritt18Route,
  AntragSchritt2Route: AntragSchritt2Route,
  AntragSchritt3Route: AntragSchritt3Route,
  AntragSchritt4Route: AntragSchritt4Route,
  AntragSchritt5Route: AntragSchritt5Route,
  AntragSchritt6Route: AntragSchritt6Route,
  AntragSchritt7Route: AntragSchritt7Route,
  AntragSchritt8Route: AntragSchritt8Route,
  AntragSchritt9Route: AntragSchritt9Route,
}

const AntragRouteRouteWithChildren = AntragRouteRoute._addFileChildren(
  AntragRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AntragRouteRoute: AntragRouteRouteWithChildren,
  AngeboteRoute: AngeboteRoute,
  AuthRoute: AuthRoute,
  BestaetigungRoute: BestaetigungRoute,
  BestellenRoute: BestellenRoute,
  BewertungenRoute: BewertungenRoute,
  FaqRoute: FaqRoute,
  HeizoelWissenRoute: HeizoelWissenRoute,
  KontaktRoute: KontaktRoute,
  LieferungZahlungRoute: LieferungZahlungRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  HeizoelpreiseCityRoute: HeizoelpreiseCityRoute,
  KreditantragApplicationIdRoute: KreditantragApplicationIdRoute,
  PreisrechnerErgebnisRoute: PreisrechnerErgebnisRoute,
  HeizoelpreiseIndexRoute: HeizoelpreiseIndexRoute,
  PreisrechnerIndexRoute: PreisrechnerIndexRoute,
  HeizoelpreiseBundeslandStateRoute: HeizoelpreiseBundeslandStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
