/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCallerRouteImport } from './routes/_authenticated/caller'
import { Route as AuthenticatedWeiterleitungRouteImport } from './routes/_authenticated/weiterleitung'
import { Route as AuthenticatedAdminBrandingsRouteImport } from './routes/_authenticated/admin_.brandings'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin_.emails'
import { Route as AuthenticatedAdminBrandingsBrandingIdRouteImport } from './routes/_authenticated/admin_.brandings_.$brandingId'
import { Route as AuthenticatedAdminBrandingsNeuRouteImport } from './routes/_authenticated/admin_.brandings_.neu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallerRoute = AuthenticatedCallerRouteImport.update({
  id: '/caller',
  path: '/caller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeiterleitungRoute =
  AuthenticatedWeiterleitungRouteImport.update({
    id: '/weiterleitung',
    path: '/weiterleitung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBrandingsRoute =
  AuthenticatedAdminBrandingsRouteImport.update({
    id: '/admin_/brandings',
    path: '/admin/brandings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/admin_/emails',
    path: '/admin/emails',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBrandingsBrandingIdRoute =
  AuthenticatedAdminBrandingsBrandingIdRouteImport.update({
    id: '/admin_/brandings_/$brandingId',
    path: '/admin/brandings/$brandingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBrandingsNeuRoute =
  AuthenticatedAdminBrandingsNeuRouteImport.update({
    id: '/admin_/brandings_/neu',
    path: '/admin/brandings/neu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/caller': typeof AuthenticatedCallerRoute
  '/weiterleitung': typeof AuthenticatedWeiterleitungRoute
  '/admin/brandings': typeof AuthenticatedAdminBrandingsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/brandings/$brandingId': typeof AuthenticatedAdminBrandingsBrandingIdRoute
  '/admin/brandings/neu': typeof AuthenticatedAdminBrandingsNeuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/caller': typeof AuthenticatedCallerRoute
  '/weiterleitung': typeof AuthenticatedWeiterleitungRoute
  '/admin/brandings': typeof AuthenticatedAdminBrandingsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/brandings/$brandingId': typeof AuthenticatedAdminBrandingsBrandingIdRoute
  '/admin/brandings/neu': typeof AuthenticatedAdminBrandingsNeuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/caller': typeof AuthenticatedCallerRoute
  '/_authenticated/weiterleitung': typeof AuthenticatedWeiterleitungRoute
  '/_authenticated/admin_/brandings': typeof AuthenticatedAdminBrandingsRoute
  '/_authenticated/admin_/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin_/brandings_/$brandingId': typeof AuthenticatedAdminBrandingsBrandingIdRoute
  '/_authenticated/admin_/brandings_/neu': typeof AuthenticatedAdminBrandingsNeuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/caller'
    | '/weiterleitung'
    | '/admin/brandings'
    | '/admin/emails'
    | '/admin/brandings/$brandingId'
    | '/admin/brandings/neu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/caller'
    | '/weiterleitung'
    | '/admin/brandings'
    | '/admin/emails'
    | '/admin/brandings/$brandingId'
    | '/admin/brandings/neu'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/caller'
    | '/_authenticated/weiterleitung'
    | '/_authenticated/admin_/brandings'
    | '/_authenticated/admin_/emails'
    | '/_authenticated/admin_/brandings_/$brandingId'
    | '/_authenticated/admin_/brandings_/neu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caller': {
      id: '/_authenticated/caller'
      path: '/caller'
      fullPath: '/caller'
      preLoaderRoute: typeof AuthenticatedCallerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weiterleitung': {
      id: '/_authenticated/weiterleitung'
      path: '/weiterleitung'
      fullPath: '/weiterleitung'
      preLoaderRoute: typeof AuthenticatedWeiterleitungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/brandings': {
      id: '/_authenticated/admin_/brandings'
      path: '/admin/brandings'
      fullPath: '/admin/brandings'
      preLoaderRoute: typeof AuthenticatedAdminBrandingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/emails': {
      id: '/_authenticated/admin_/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/brandings_/$brandingId': {
      id: '/_authenticated/admin_/brandings_/$brandingId'
      path: '/admin/brandings/$brandingId'
      fullPath: '/admin/brandings/$brandingId'
      preLoaderRoute: typeof AuthenticatedAdminBrandingsBrandingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/brandings_/neu': {
      id: '/_authenticated/admin_/brandings_/neu'
      path: '/admin/brandings/neu'
      fullPath: '/admin/brandings/neu'
      preLoaderRoute: typeof AuthenticatedAdminBrandingsNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCallerRoute: typeof AuthenticatedCallerRoute
  AuthenticatedWeiterleitungRoute: typeof AuthenticatedWeiterleitungRoute
  AuthenticatedAdminBrandingsRoute: typeof AuthenticatedAdminBrandingsRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminBrandingsBrandingIdRoute: typeof AuthenticatedAdminBrandingsBrandingIdRoute
  AuthenticatedAdminBrandingsNeuRoute: typeof AuthenticatedAdminBrandingsNeuRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCallerRoute: AuthenticatedCallerRoute,
  AuthenticatedWeiterleitungRoute: AuthenticatedWeiterleitungRoute,
  AuthenticatedAdminBrandingsRoute: AuthenticatedAdminBrandingsRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminBrandingsBrandingIdRoute:
    AuthenticatedAdminBrandingsBrandingIdRoute,
  AuthenticatedAdminBrandingsNeuRoute: AuthenticatedAdminBrandingsNeuRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
