// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdlhjoxmxryquecocwjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkbGhqb3hteHJ5cXVlY29jd2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkzNjQ0NjgsImV4cCI6MjEwNDk0MDQ2OH0.rfh4pUYIKrJTkamO9xExEp_0LqPzWbqMDJfDfL3yMpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});